CREATE DATABASE tiendaProyecto;
USE tiendaProyecto;

CREATE TABLE PERSONAS(
ID_PERSONA 		NUMERIC(12),
NOM_PERSONA		VARCHAR(50)		NOT NULL,
APE_PERSONA		VARCHAR(50)		NOT NULL,
TEL_PERSONA		NUMERIC(10)		NOT NULL,
EMAIL_PERSONA	VARCHAR(50)		NOT NULL,
DIR_PERSONA		VARCHAR(100)	NOT NULL,
CONTRASENA		VARCHAR(8),
TIPO_PERSONA	VARCHAR(3),
CONSTRAINT PK_PERSONAS PRIMARY KEY(ID_PERSONA, TIPO_PERSONA));

CREATE TABLE CATEGORIAS(
ID_CATEGORIA		INT			PRIMARY KEY		IDENTITY(1, 1),
NOM_CATEGORIA		VARCHAR(50)	NOT NULL,
ID_CATEGORIA_PADRE	INT,
FOREIGN KEY (ID_CATEGORIA_PADRE) REFERENCES CATEGORIAS (ID_CATEGORIA));

CREATE TABLE FABRICANTES(
ID_FABRICANTE		INT			PRIMARY KEY		IDENTITY(1, 1),
NOM_FABRICANTE		VARCHAR(50)	NOT NULL,
PAIS_FABRICANTE		VARCHAR(3)	NOT NULL);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO		INT				PRIMARY KEY			IDENTITY(1,1),
NOM_PRODUCTO	VARCHAR(50)		NOT NULL,
DET_PRODUCTO	VARCHAR(300)	NOT NULL,
PRECIO_ACTUAL	NUMERIC(10)		NOT NULL,
UND_DISPONIBLES	INT				NOT NULL	DEFAULT(0),
ID_CATEGORIA	INT				NOT NULL,
ID_FABRICANTE	INT				NOT NULL,
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA),
FOREIGN KEY (ID_FABRICANTE) REFERENCES FABRICANTES (ID_FABRICANTE));

CREATE TABLE VENTAS(
ID_VENTA		INT			PRIMARY KEY			IDENTITY(1,1),
FECHA_VENTA		DATE		NOT NULL,
VLR_IVA			NUMERIC(10)	NOT NULL,
ID_PERSONA		NUMERIC(12)	NOT NULL,
TIPO_PERSONA	VARCHAR(3)	NOT NULL,
FOREIGN KEY (ID_PERSONA, TIPO_PERSONA) 
	REFERENCES PERSONAS(ID_PERSONA, TIPO_PERSONA));

CREATE TABLE VENTA_PRODUCTOS(
ID_VENTA_PROD		INT 		PRIMARY KEY		IDENTITY(1,1),
ID_VENTA			INT			NOT NULL,
ID_PRODUCTO			INT			NOT NULL,
PRECIO_VENTA		NUMERIC(10)	NOT NULL,
CANTIDAD			INT			NOT NULL,
FOREIGN KEY (ID_VENTA) REFERENCES VENTAS (ID_VENTA),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO));

CREATE TABLE [dbo].[DOMINIOS](
	[TIPO_DOMINIO] [varchar](50) NOT NULL,
	[ID_DOMINIO] [varchar](3) NOT NULL,
	[VLR_DOMINIO] [varchar](50) NULL,
 CONSTRAINT [PK_DOMINIOS] PRIMARY KEY CLUSTERED 
(
	[TIPO_DOMINIO] ASC,
	[ID_DOMINIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO DOMINIOS VALUES
('PAISES', 'GER', 'GERMANY'),
('PAISES', 'ENG', 'ENGLAND'),
('PAISES', 'FRA', 'FRANCE'),
('PAISES', 'USA', 'ESTADOS UNIDOS'),
('PAISES', 'SPA', 'SPAIN'),
('PAISES', 'COL', 'COLOMBIA'),
('PAISES', 'BRA', 'BRAZIL'),
('PAISES', 'MEX', 'MEXICO');










